CREATE table 2019_09_23_20_27(
  UID VARCHAR(10),
  PID INTEGER,
  PPID INTEGER,
  C INTEGER,
  SZ INTEGER,
  RSS INTEGER,
  PSR INTEGER,
  STIME VARCHAR(14),
  TTY VARCHAR(10),
  TIME VARCHAR(8),
  CMD VARCHAR(70),
  ENDTIME VARCHAR(8),
  LIVE VARCHAR(7),
  PRIMARY KEY (PID)
);
