CREATE table monitoring_system(
  UID VARCHAR,
  PID INTEGER,
  PPID INTEGER,
  C INTEGER,
  SZ INTEGER,
  RSS INTEGER,
  PSR INTEGER,
  STIME VARCHAR,
  TTY VARCHAR,
  TIME VARCHAR,
  CMD VARCHAR,
  PRIMARY KEY (PID)
);